// ============================================================
// DATA — Sri Subramaniar Alayam Kiosk App
// Static, developer-owned config: interface text (3 languages) and
// home-tile blurbs. This is NOT CMS-managed — it rarely changes and
// isn't "temple content." Everything the CMS edits (deities, events,
// sevas, announcements, gallery, about, contact, pooja timings) lives
// in /content/*.json and is compiled into content-data.js by build.js
// on every deploy. index.html loads this file, then content-data.js,
// then script.js.
// ============================================================

// ---------- UI chrome strings (nav, buttons, labels, headings) ----------
const UI = {
  en: {
    navHome: "Home", navAbout: "About Temple", navCommittee: "Temple Committee", navDeities: "Deities",
    railBrandLine1: "Sri Subramaniar", railBrandLine2: "Alayam", railBrandLoc: "Lok Kawi, Kota Kinabalu",
    navCalendar: "Event Calendar", navTimings: "Pooja Timings", navGallery: "Gallery",
    navSevas: "Sevas & Donations", navNews: "News & Announcements",
    navMembership: "Membership Status", navContact: "Contact Us",
    railHoursTitle: "Temple Hours — Daily", railMorning: "Morning", railEvening: "Evening",
    heroEyebrow: "Welcome to",
    heroTitleLine1: "Sri Subramaniar Alayam", heroTitleLine2: "Lok Kawi",
    statEstablished: "Established", statDevotees: "Devotees", statEvents: "Annual Events",
    heroBtnEvents: "Upcoming Events", heroBtnTimings: "Pooja Timings",
    panelTodayTimings: "TODAY'S POOJA TIMES", panelUpcomingEvents: "UPCOMING EVENTS",
    panelNewsAnnouncements: "NEWS & ANNOUNCEMENTS",
    btnViewFullTimings: "View Full Timings →", btnViewFullCalendar: "View Full Calendar →",
    btnNewsAnnouncements: "News & Announcements →",
    velBlessing: "Vel! Vel! Vetri Vel!",
    velBlessingDesc: "May Lord Murugan bless you and your family with peace, prosperity & good health.",
    subscribePlaceholder: "Enter your email", subscribeBtn: "Subscribe",
    aboutHeading: "About the Temple", aboutSub: "History, vision, and daily life at Sri Subramaniar Alayam.",
    aboutHistoryTitle: "Our History", aboutVisionTitle: "Vision", aboutMissionTitle: "Mission",
    aboutActivitiesTitle: "Temple Activities",
    committeeHeading: "Temple Management Committee", committeeSub: "Meet the committee members serving Sri Subramaniar Alayam.",
    committeeOfficersLabel: "Officers", committeeMembersLabel: "Committee Members",
    committeeAuditorsLabel: "Internal Auditors", committeeTrusteesLabel: "Trustees",
    deitiesHeading: "Deities", deitiesSub: "Sri Subramaniar and the shrines within our temple complex.",
    calendarHeading: "Event Calendar", calendarSub: "Upcoming poojas, festivals, and special events.",
    calToday: "Today", calEventsSuffix: "Events", calNoEvents: "No events on record for this month.", readMoreBtn: "More",
    timingsHeading: "Pooja Timings", timingsSub: "Daily schedule of poojas and special-day timings.",
    galleryHeading: "Gallery", gallerySub: "Moments from festivals, poojas, and community events.",
    galleryBack: "Back", galleryEmpty: "No categories yet.", galleryFoldersEmpty: "No folders yet.", galleryPhotosEmpty: "No photos yet.",
    sevasHeading: "Sevas & Donations", sevasSub: "Support the temple through sevas, sponsorships, and donations.",
    donateBannerTitle: "Every contribution matters",
    donateBannerDesc: "Your generosity keeps daily poojas, festivals, and community programs running for thousands of devotees.",
    newsHeading: "News & Announcements", newsSub: "The latest updates from the temple.",
    membershipHeading: "Membership Status", membershipSub: "Enter your Membership No. to check your temple membership status.",
    membershipInputLabel: "Membership No.", membershipPlaceholder: "M-0231",
    membershipCheckBtn: "Check Status", membershipChecking: "Checking…",
    membershipHint: "Enter the Membership No. shown on your membership card.",
    membershipInvalidFormat: "Please enter your Membership No.",
    membershipNotFound: "No membership record was found for this Membership No.",
    membershipError: "Something went wrong. Please try again in a moment.",
    membershipResultName: "Name", membershipResultNo: "Membership No.",
    membershipResultType: "Membership Type", membershipTypeLife: "Life", membershipTypeOrdinary: "Ordinary",
    membershipResultStatus: "Status", membershipStatusActive: "Active", membershipStatusNotActive: "Not Active",
    membershipStatusPending: "Pending for Annual Renewal", membershipPrintBtn: "Print",
    contactHeading: "Contact Us", contactSub: "Visit, call, or write to us.",
    getInTouch: "Get in Touch", regNoLabel: "Reg. No", phoneLabel: "Phone",
    emailLabel: "Email", followLabel: "Follow Us",
    enquiriesTitle: "For Any Enquiries", whatsappCaption: "Scan to chat with us on WhatsApp",
    qrScanToPay: "Scan to Pay", qrAccountName: "Account Name", qrBank: "Bank",
    qrAccountNo: "Account No.", qrNote: "Scan with any DuitNow-enabled banking or e-wallet app.",
    idleReturning: "Returning to Home…",
    timingTabDaily: "Daily", timingTabFriday: "Friday (Special)", timingTabFullMoon: "Full Moon (Pournami)",
    navPrayers: "Prayers & Registration",
    navFridayAnnathanam: "Friday Annathanam",
    prayersHeading: "Annual Prayers & Registration", prayersSub: "Sponsor a pooja as Ubayakarar or Annathanam sponsor, or register as a participant.",
    prayersCategoryAnnual: "Annual Prayers/Poojas", prayersCategoryMonthly: "Monthly Prayers/Poojas", prayersCategorySpecial: "Special Prayers/Poojas",
    prayersFilterAll: "All", prayersFilterUpcoming: "Upcoming", prayersFilterOver: "Completed",
    prayersStatusUpcoming: "Upcoming", prayersStatusOver: "Completed",
    prayersUbayakararLabel: "Ubayakarar", prayersAnnathanamLabel: "Annathanam Sponsor", prayersParticipantLabel: "Participant",
    prayersOpenBadge: "Open", prayersTakenBadge: "Reserved", prayersClosedBadge: "Registration Closed", prayersPaidBadge: "Paid", prayersNotPaidBadge: "Not Paid", prayersConfirmedBadge: "Confirmed", prayersNotConfirmedBadge: "Not Confirmed",
    prayersRegisterBtn: "Register", prayersFeeLabel: "Ubayam Fee", prayersPerPersonLabel: "Per Person", prayersAsArranged: "As arranged",
    prayersCaterersHeading: "Annathanam Caterers", prayersCaterersSub: "Prefer to arrange the meal yourself? Contact any of our regular caterers directly.",
    prayersParticipantsHeading: "Registered Participants", prayersNoParticipants: "No participant registrations were recorded for this pooja.",
    prayersNotesLabel: "Notes",
    prayersModalUbayakararTitle: "Register as Ubayakarar", prayersModalAnnathanamTitle: "Register as Annathanam Sponsor", prayersModalParticipantTitle: "Register as Participant",
    prayersFormName: "Full Name", prayersFormPhone: "Phone / WhatsApp Number", prayersFormParticipantCount: "Number of Participants (No. of Pax)",
    prayersFormParticipantCountHint: "Registering as a family or group? Enter the total headcount here — e.g. 5 if a family of 5 is attending together. One registration covers everyone.",
    prayersPaxLabel: "pax",
    prayersFormNotes: "Remarks (optional)", prayersFormSubmit: "Submit Registration", prayersFormSubmitting: "Submitting…", prayersFormCancel: "Cancel",
    prayersSuccessTitle: "Registration received!", prayersSuccessRef: "Reference",
    prayersSuccessUbayakarar: "Please complete payment via bank transfer or DuitNow QR, then send your proof of payment via WhatsApp, quoting your reference above.",
    prayersSuccessAnnathanam: "Your Annathanam sponsorship is reserved. Please contact your preferred caterer directly to arrange the meal — see the caterer list below.",
    prayersSuccessParticipantPaid: "Please complete payment via bank transfer or DuitNow QR, then send your proof of payment via WhatsApp, quoting your reference above.",
    prayersSuccessParticipantFree: "You're registered. We look forward to seeing you there!",
    prayersErrorGeneric: "Something went wrong. Please try again in a moment.", prayersCloseBtn: "Close",
    fridayAnnathanamHeading: "Weekly Friday Pooja Annathanam",
    fridayAnnathanamSub: "RM 250 sponsors the temple's Annathanam meal for one Friday. Choose any open Friday below to sponsor it — payment is by bank transfer or DuitNow QR.",
    fridayAnnathanamOpenBadge: "Open", fridayAnnathanamSponsoredBadge: "Sponsored", fridayAnnathanamSkippedBadge: "No Annathanam",
    fridayAnnathanamSponsorBtn: "Sponsor This Friday", fridayAnnathanamModalTitle: "Sponsor Friday Annathanam",
    fridayAnnathanamSuccessMessage: "Your Friday Annathanam sponsorship is reserved. Please complete payment via bank transfer or DuitNow QR, then send your proof of payment via WhatsApp, quoting your reference above.",
    fridayAnnathanamNoUpcoming: "No Fridays are listed yet — please check back soon."
  },
  bm: {
    navHome: "Utama", navAbout: "Tentang Kuil", navCommittee: "Jawatankuasa Kuil", navDeities: "Dewa-Dewi",
    railBrandLine1: "Sri Subramaniar", railBrandLine2: "Alayam", railBrandLoc: "Lok Kawi, Kota Kinabalu",
    navCalendar: "Kalendar Acara", navTimings: "Waktu Pooja", navGallery: "Galeri",
    navSevas: "Seva & Derma", navNews: "Berita & Pengumuman",
    navMembership: "Status Keahlian", navContact: "Hubungi Kami",
    railHoursTitle: "Waktu Kuil — Setiap Hari", railMorning: "Pagi", railEvening: "Petang",
    heroEyebrow: "Selamat Datang ke",
    heroTitleLine1: "Sri Subramaniar Alayam", heroTitleLine2: "Lok Kawi",
    statEstablished: "Ditubuhkan", statDevotees: "Penganut", statEvents: "Acara Tahunan",
    heroBtnEvents: "Acara Akan Datang", heroBtnTimings: "Waktu Pooja",
    panelTodayTimings: "WAKTU POOJA HARI INI", panelUpcomingEvents: "ACARA AKAN DATANG",
    panelNewsAnnouncements: "BERITA & PENGUMUMAN",
    btnViewFullTimings: "Lihat Semua Waktu →", btnViewFullCalendar: "Lihat Kalendar Penuh →",
    btnNewsAnnouncements: "Berita & Pengumuman →",
    velBlessing: "Vel! Vel! Vetri Vel!",
    velBlessingDesc: "Semoga Dewa Murugan melimpahkan keamanan, kemakmuran dan kesihatan yang baik kepada anda sekeluarga.",
    subscribePlaceholder: "Masukkan e-mel anda", subscribeBtn: "Langgan",
    aboutHeading: "Tentang Kuil", aboutSub: "Sejarah, visi, dan kehidupan seharian di Sri Subramaniar Alayam.",
    aboutHistoryTitle: "Sejarah Kami", aboutVisionTitle: "Visi", aboutMissionTitle: "Misi",
    aboutActivitiesTitle: "Aktiviti Kuil",
    committeeHeading: "Jawatankuasa Pengurusan Kuil", committeeSub: "Kenali ahli jawatankuasa yang berkhidmat di Sri Subramaniar Alayam.",
    committeeOfficersLabel: "Pegawai", committeeMembersLabel: "Ahli Jawatankuasa",
    committeeAuditorsLabel: "Juruaudit Dalaman", committeeTrusteesLabel: "Pemegang Amanah",
    deitiesHeading: "Dewa-Dewi", deitiesSub: "Sri Subramaniar dan dewa-dewi lain di dalam kompleks kuil kami.",
    calendarHeading: "Kalendar Acara", calendarSub: "Pooja, perayaan dan acara khas yang akan datang.",
    calToday: "Hari Ini", calEventsSuffix: "Acara", calNoEvents: "Tiada acara direkodkan untuk bulan ini.", readMoreBtn: "Lagi",
    timingsHeading: "Waktu Pooja", timingsSub: "Jadual pooja harian dan waktu pada hari-hari istimewa.",
    galleryHeading: "Galeri", gallerySub: "Detik-detik berharga daripada perayaan, pooja dan acara komuniti.",
    galleryBack: "Kembali", galleryEmpty: "Belum ada kategori.", galleryFoldersEmpty: "Belum ada folder.", galleryPhotosEmpty: "Belum ada foto.",
    sevasHeading: "Seva & Derma", sevasSub: "Sokong kuil melalui seva, penajaan, dan derma.",
    donateBannerTitle: "Setiap sumbangan amat bermakna",
    donateBannerDesc: "Kemurahan hati anda membolehkan pooja harian, perayaan dan program komuniti terus berjalan demi manfaat ribuan penganut.",
    newsHeading: "Berita & Pengumuman", newsSub: "Perkembangan terkini daripada pihak kuil.",
    membershipHeading: "Status Keahlian", membershipSub: "Masukkan No. Keahlian anda untuk menyemak status keahlian anda di kuil.",
    membershipInputLabel: "No. Keahlian", membershipPlaceholder: "M-0231",
    membershipCheckBtn: "Semak Status", membershipChecking: "Menyemak…",
    membershipHint: "Masukkan No. Keahlian yang tertera pada kad keahlian anda.",
    membershipInvalidFormat: "Sila masukkan No. Keahlian anda.",
    membershipNotFound: "Tiada rekod keahlian dijumpai untuk No. Keahlian ini.",
    membershipError: "Maaf, berlaku ralat. Sila cuba sebentar lagi.",
    membershipResultName: "Nama", membershipResultNo: "No. Keahlian",
    membershipResultType: "Jenis Keahlian", membershipTypeLife: "Seumur Hidup", membershipTypeOrdinary: "Biasa",
    membershipResultStatus: "Status", membershipStatusActive: "Aktif", membershipStatusNotActive: "Tidak Aktif",
    membershipStatusPending: "Menunggu Pembaharuan Tahunan", membershipPrintBtn: "Cetak",
    contactHeading: "Hubungi Kami", contactSub: "Datanglah melawat, hubungi atau hantar mesej kepada kami.",
    getInTouch: "Hubungi Kami", regNoLabel: "No. Pendaftaran", phoneLabel: "Telefon",
    emailLabel: "E-mel", followLabel: "Ikuti Kami",
    enquiriesTitle: "Sebarang Pertanyaan", whatsappCaption: "Imbas untuk berbual dengan kami di WhatsApp",
    qrScanToPay: "Imbas untuk Bayar", qrAccountName: "Nama Akaun", qrBank: "Bank",
    qrAccountNo: "No. Akaun", qrNote: "Imbas menggunakan mana-mana aplikasi perbankan atau e-dompet yang menyokong DuitNow.",
    idleReturning: "Kembali ke Halaman Utama…",
    timingTabDaily: "Harian", timingTabFriday: "Jumaat (Khas)", timingTabFullMoon: "Pournami (Bulan Purnama)",
    navPrayers: "Pooja Tahunan & Pendaftaran",
    navFridayAnnathanam: "Annathanam Jumaat",
    prayersHeading: "Pooja Tahunan & Pendaftaran", prayersSub: "Taja pooja sebagai Ubayakarar atau penaja Annathanam, atau daftar sebagai peserta.",
    prayersCategoryAnnual: "Pooja Tahunan", prayersCategoryMonthly: "Pooja Bulanan", prayersCategorySpecial: "Pooja Khas",
    prayersFilterAll: "Semua", prayersFilterUpcoming: "Akan Datang", prayersFilterOver: "Selesai",
    prayersStatusUpcoming: "Akan Datang", prayersStatusOver: "Selesai",
    prayersUbayakararLabel: "Ubayakarar", prayersAnnathanamLabel: "Penaja Annathanam", prayersParticipantLabel: "Peserta",
    prayersOpenBadge: "Terbuka", prayersTakenBadge: "Ditempah", prayersClosedBadge: "Pendaftaran Ditutup", prayersPaidBadge: "Dibayar", prayersNotPaidBadge: "Belum Dibayar", prayersConfirmedBadge: "Disahkan", prayersNotConfirmedBadge: "Belum Disahkan",
    prayersRegisterBtn: "Daftar", prayersFeeLabel: "Yuran Ubayam", prayersPerPersonLabel: "Setiap Orang", prayersAsArranged: "Mengikut persetujuan",
    prayersCaterersHeading: "Katerer Annathanam", prayersCaterersSub: "Ingin menguruskan hidangan sendiri? Hubungi terus mana-mana katerer tetap kami.",
    prayersParticipantsHeading: "Peserta Berdaftar", prayersNoParticipants: "Tiada pendaftaran peserta direkodkan untuk pooja ini.",
    prayersNotesLabel: "Catatan",
    prayersModalUbayakararTitle: "Daftar sebagai Ubayakarar", prayersModalAnnathanamTitle: "Daftar sebagai Penaja Annathanam", prayersModalParticipantTitle: "Daftar sebagai Peserta",
    prayersFormName: "Nama Penuh", prayersFormPhone: "Nombor Telefon / WhatsApp", prayersFormParticipantCount: "Bilangan Peserta (Jumlah Orang)",
    prayersFormParticipantCountHint: "Mendaftar sebagai keluarga atau kumpulan? Masukkan jumlah keseluruhan orang di sini — cth. 5 jika seisi keluarga seramai 5 orang hadir bersama. Satu pendaftaran meliputi semua.",
    prayersPaxLabel: "orang",
    prayersFormNotes: "Catatan (pilihan)", prayersFormSubmit: "Hantar Pendaftaran", prayersFormSubmitting: "Menghantar…", prayersFormCancel: "Batal",
    prayersSuccessTitle: "Pendaftaran diterima!", prayersSuccessRef: "Rujukan",
    prayersSuccessUbayakarar: "Sila lengkapkan pembayaran melalui pemindahan bank atau QR DuitNow, kemudian hantar bukti pembayaran melalui WhatsApp beserta nombor rujukan di atas.",
    prayersSuccessAnnathanam: "Penajaan Annathanam anda telah ditempah. Sila hubungi terus katerer pilihan anda untuk menguruskan hidangan — lihat senarai katerer di bawah.",
    prayersSuccessParticipantPaid: "Sila lengkapkan pembayaran melalui pemindahan bank atau QR DuitNow, kemudian hantar bukti pembayaran melalui WhatsApp beserta nombor rujukan di atas.",
    prayersSuccessParticipantFree: "Anda telah berdaftar. Kami mengalu-alukan kehadiran anda!",
    prayersErrorGeneric: "Maaf, berlaku ralat. Sila cuba sebentar lagi.", prayersCloseBtn: "Tutup",
    fridayAnnathanamHeading: "Annathanam Pooja Jumaat Mingguan",
    fridayAnnathanamSub: "Penajaan hidangan Annathanam kuil untuk satu hari Jumaat berharga RM 250. Pilih mana-mana hari Jumaat yang masih terbuka di bawah — pembayaran melalui pemindahan bank atau QR DuitNow.",
    fridayAnnathanamOpenBadge: "Terbuka", fridayAnnathanamSponsoredBadge: "Ditaja", fridayAnnathanamSkippedBadge: "Tiada Annathanam",
    fridayAnnathanamSponsorBtn: "Taja Jumaat Ini", fridayAnnathanamModalTitle: "Taja Annathanam Jumaat",
    fridayAnnathanamSuccessMessage: "Penajaan Annathanam Jumaat anda telah ditempah. Sila lengkapkan pembayaran melalui pemindahan bank atau QR DuitNow, kemudian hantar bukti pembayaran melalui WhatsApp beserta nombor rujukan di atas.",
    fridayAnnathanamNoUpcoming: "Belum ada hari Jumaat disenaraikan — sila semak semula nanti."
  },
  ta: {
    navHome: "முகப்பு", navAbout: "கோயில் பற்றி", navCommittee: "கோயில் குழு", navDeities: "தெய்வங்கள்",
    railBrandLine1: "ஸ்ரீ சுப்ரமணியர்", railBrandLine2: "ஆலயம்", railBrandLoc: "லோக் காவி, கோத்தா கினபாலு",
    navCalendar: "நிகழ்வு நாட்காட்டி", navTimings: "பூஜை நேரங்கள்", navGallery: "படத்தொகுப்பு",
    navSevas: "சேவை & நன்கொடை", navNews: "செய்திகள் & அறிவிப்புகள்",
    navMembership: "உறுப்பினர் நிலை", navContact: "தொடர்பு கொள்ள",
    railHoursTitle: "கோயில் நேரம் — தினமும்", railMorning: "காலை", railEvening: "மாலை",
    heroEyebrow: "வருக",
    heroTitleLine1: "ஸ்ரீ சுப்ரமணியர் ஆலயம்", heroTitleLine2: "லோக் காவி",
    statEstablished: "நிறுவப்பட்ட ஆண்டு", statDevotees: "பக்தர்கள்", statEvents: "ஆண்டு நிகழ்வுகள்",
    heroBtnEvents: "வரவிருக்கும் நிகழ்வுகள்", heroBtnTimings: "பூஜை நேரங்கள்",
    panelTodayTimings: "இன்றைய பூஜை நேரங்கள்", panelUpcomingEvents: "வரவிருக்கும் நிகழ்வுகள்",
    panelNewsAnnouncements: "செய்திகள் & அறிவிப்புகள்",
    btnViewFullTimings: "முழு நேரங்களைக் காண →", btnViewFullCalendar: "முழு நாட்காட்டியைக் காண →",
    btnNewsAnnouncements: "செய்திகள் & அறிவிப்புகள் →",
    velBlessing: "வேல்! வேல்! வெற்றி வேல்!",
    velBlessingDesc: "முருகப்பெருமான் உங்களையும் உங்கள் குடும்பத்தையும் அமைதி, செழிப்பு மற்றும் நல்வாழ்வுடன் ஆசீர்வதிக்கட்டும்.",
    subscribePlaceholder: "உங்கள் மின்னஞ்சலை உள்ளிடவும்", subscribeBtn: "சந்தா செய்யவும்",
    aboutHeading: "கோயில் பற்றி", aboutSub: "ஸ்ரீ சுப்ரமணியர் ஆலயத்தின் வரலாறு, நோக்கம் மற்றும் அன்றாட வாழ்க்கை.",
    aboutHistoryTitle: "எங்கள் வரலாறு", aboutVisionTitle: "நோக்கம்", aboutMissionTitle: "பணி",
    aboutActivitiesTitle: "கோயில் நடவடிக்கைகள்",
    committeeHeading: "கோயில் நிர்வாகக் குழு", committeeSub: "ஸ்ரீ சுப்ரமணியர் ஆலயத்தில் பணியாற்றும் குழு உறுப்பினர்களை அறிந்து கொள்ளுங்கள்.",
    committeeOfficersLabel: "பொறுப்பாளர்கள்", committeeMembersLabel: "குழு உறுப்பினர்கள்",
    committeeAuditorsLabel: "உள் தணிக்கையாளர்கள்", committeeTrusteesLabel: "அறங்காவலர்கள்",
    deitiesHeading: "தெய்வங்கள்", deitiesSub: "எங்கள் கோயில் வளாகத்தில் உள்ள ஸ்ரீ சுப்ரமணியரும் பிற தெய்வங்களும்.",
    calendarHeading: "நிகழ்வு நாட்காட்டி", calendarSub: "வரவிருக்கும் பூஜைகள், திருவிழாக்கள் மற்றும் சிறப்பு நிகழ்வுகள்.",
    calToday: "இன்று", calEventsSuffix: "நிகழ்வுகள்", calNoEvents: "இந்த மாதத்திற்கு நிகழ்வுகள் எதுவும் பதிவு செய்யப்படவில்லை.", readMoreBtn: "மேலும்",
    timingsHeading: "பூஜை நேரங்கள்", timingsSub: "தினசரி பூஜை அட்டவணை மற்றும் சிறப்பு நாள் நேரங்கள்.",
    galleryHeading: "படத்தொகுப்பு", gallerySub: "திருவிழாக்கள், பூஜைகள் மற்றும் சமூக நிகழ்வுகளின் தருணங்கள்.",
    galleryBack: "பின்", galleryEmpty: "இன்னும் வகைகள் இல்லை.", galleryFoldersEmpty: "இன்னும் கோப்புறைகள் இல்லை.", galleryPhotosEmpty: "இன்னும் புகைப்படங்கள் இல்லை.",
    sevasHeading: "சேவை & நன்கொடை", sevasSub: "சேவைகள், நிதியுதவி மற்றும் நன்கொடைகள் மூலம் கோயிலுக்கு ஆதரவளியுங்கள்.",
    donateBannerTitle: "ஒவ்வொரு பங்களிப்பும் முக்கியம்",
    donateBannerDesc: "உங்கள் தாராள மனப்பான்மை ஆயிரக்கணக்கான பக்தர்களுக்காக தினசரி பூஜைகள், திருவிழாக்கள் மற்றும் சமூக நிகழ்ச்சிகளை நடத்த உதவுகிறது.",
    newsHeading: "செய்திகள் & அறிவிப்புகள்", newsSub: "கோயிலின் சமீபத்திய புதுப்பிப்புகள்.",
    membershipHeading: "உறுப்பினர் நிலை", membershipSub: "உங்கள் கோயில் உறுப்பினர் நிலையைச் சரிபார்க்க உங்கள் உறுப்பினர் எண்ணை உள்ளிடவும்.",
    membershipInputLabel: "உறுப்பினர் எண்", membershipPlaceholder: "M-0231",
    membershipCheckBtn: "நிலையைச் சரிபார்க்க", membershipChecking: "சரிபார்க்கிறது…",
    membershipHint: "உங்கள் உறுப்பினர் அட்டையில் உள்ள உறுப்பினர் எண்ணை உள்ளிடவும்.",
    membershipInvalidFormat: "உங்கள் உறுப்பினர் எண்ணை உள்ளிடவும்.",
    membershipNotFound: "இந்த உறுப்பினர் எண்ணுக்கு உறுப்பினர் பதிவு எதுவும் கிடைக்கவில்லை.",
    membershipError: "ஏதோ தவறு நடந்தது. சிறிது நேரத்தில் மீண்டும் முயற்சிக்கவும்.",
    membershipResultName: "பெயர்", membershipResultNo: "உறுப்பினர் எண்",
    membershipResultType: "உறுப்பினர் வகை", membershipTypeLife: "வாழ்நாள்", membershipTypeOrdinary: "சாதாரண",
    membershipResultStatus: "நிலை", membershipStatusActive: "செயலில்", membershipStatusNotActive: "செயலற்றது",
    membershipStatusPending: "வருடாந்திர புதுப்பித்தலுக்கு நிலுவையில்", membershipPrintBtn: "அச்சிடு",
    contactHeading: "தொடர்பு கொள்ள", contactSub: "வருகை தரவும், அழைக்கவும், அல்லது எழுதவும்.",
    getInTouch: "எங்களைத் தொடர்பு கொள்ளுங்கள்", regNoLabel: "பதிவு எண்", phoneLabel: "தொலைபேசி",
    emailLabel: "மின்னஞ்சல்", followLabel: "எங்களைப் பின்தொடரவும்",
    enquiriesTitle: "எந்த விசாரணைக்கும்", whatsappCaption: "WhatsApp இல் எங்களுடன் அரட்டையடிக்க ஸ்கேன் செய்யவும்",
    qrScanToPay: "செலுத்த ஸ்கேன் செய்யவும்", qrAccountName: "கணக்கு பெயர்", qrBank: "வங்கி",
    qrAccountNo: "கணக்கு எண்", qrNote: "DuitNow ஆதரிக்கும் எந்த வங்கி அல்லது இ-வாலெட் செயலியிலும் ஸ்கேன் செய்யவும்.",
    idleReturning: "முகப்புக்குத் திரும்புகிறது…",
    timingTabDaily: "தினமும்", timingTabFriday: "வெள்ளி (சிறப்பு)", timingTabFullMoon: "பௌர்ணமி (முழு நிலவு)",
    navPrayers: "ஆண்டு பூஜைகள் & பதிவு",
    navFridayAnnathanam: "வெள்ளி அன்னதானம்",
    prayersHeading: "ஆண்டு பூஜைகள் & பதிவு", prayersSub: "உபயகாரராகவோ அன்னதான நிதியுதவியாளராகவோ பூஜையை நிதியுதவி செய்யுங்கள், அல்லது பங்கேற்பாளராக பதிவு செய்யுங்கள்.",
    prayersCategoryAnnual: "ஆண்டு பூஜைகள்", prayersCategoryMonthly: "மாதாந்திர பூஜைகள்", prayersCategorySpecial: "சிறப்பு பூஜைகள்",
    prayersFilterAll: "அனைத்தும்", prayersFilterUpcoming: "வரவிருக்கும்", prayersFilterOver: "முடிந்தது",
    prayersStatusUpcoming: "வரவிருக்கும்", prayersStatusOver: "முடிந்தது",
    prayersUbayakararLabel: "உபயகாரர்", prayersAnnathanamLabel: "அன்னதான நிதியுதவியாளர்", prayersParticipantLabel: "பங்கேற்பாளர்",
    prayersOpenBadge: "திறந்துள்ளது", prayersTakenBadge: "பதிவு செய்யப்பட்டது", prayersClosedBadge: "பதிவு மூடப்பட்டது", prayersPaidBadge: "செலுத்தப்பட்டது", prayersNotPaidBadge: "செலுத்தப்படவில்லை", prayersConfirmedBadge: "உறுதிப்படுத்தப்பட்டது", prayersNotConfirmedBadge: "உறுதிப்படுத்தப்படவில்லை",
    prayersRegisterBtn: "பதிவு செய்ய", prayersFeeLabel: "உபயம் கட்டணம்", prayersPerPersonLabel: "ஒருவருக்கு", prayersAsArranged: "ஏற்பாடு செய்யப்படும்",
    prayersCaterersHeading: "அன்னதான கேட்டரர்கள்", prayersCaterersSub: "நீங்களே உணவை ஏற்பாடு செய்ய விரும்புகிறீர்களா? எங்கள் வழக்கமான கேட்டரர்களை நேரடியாக தொடர்பு கொள்ளுங்கள்.",
    prayersParticipantsHeading: "பதிவு செய்த பங்கேற்பாளர்கள்", prayersNoParticipants: "இந்த பூஜைக்கு பங்கேற்பாளர் பதிவுகள் எதுவும் பதிவு செய்யப்படவில்லை.",
    prayersNotesLabel: "குறிப்புகள்",
    prayersModalUbayakararTitle: "உபயகாரராக பதிவு செய்ய", prayersModalAnnathanamTitle: "அன்னதான நிதியுதவியாளராக பதிவு செய்ய", prayersModalParticipantTitle: "பங்கேற்பாளராக பதிவு செய்ய",
    prayersFormName: "முழு பெயர்", prayersFormPhone: "தொலைபேசி / WhatsApp எண்", prayersFormParticipantCount: "பங்கேற்பாளர்கள் எண்ணிக்கை (எத்தனை பேர்)",
    prayersFormParticipantCountHint: "குடும்பமாகவோ குழுவாகவோ பதிவு செய்கிறீர்களா? மொத்த எண்ணிக்கையை இங்கே உள்ளிடவும் — எ.கா. 5 பேர் கொண்ட குடும்பம் எனில் 5 எனப் பதிவிடவும். ஒரே பதிவு அனைவரையும் உள்ளடக்கும்.",
    prayersPaxLabel: "பேர்",
    prayersFormNotes: "குறிப்புகள் (விருப்பம்)", prayersFormSubmit: "பதிவை சமர்ப்பிக்க", prayersFormSubmitting: "சமர்ப்பிக்கிறது…", prayersFormCancel: "ரத்து செய்",
    prayersSuccessTitle: "பதிவு பெறப்பட்டது!", prayersSuccessRef: "குறிப்பு எண்",
    prayersSuccessUbayakarar: "வங்கி பரிமாற்றம் அல்லது DuitNow QR மூலம் பணம் செலுத்தி, மேலே உள்ள குறிப்பு எண்ணுடன் WhatsApp மூலம் பணம் செலுத்திய சான்றை அனுப்பவும்.",
    prayersSuccessAnnathanam: "உங்கள் அன்னதான நிதியுதவி பதிவு செய்யப்பட்டுள்ளது. உணவை ஏற்பாடு செய்ய உங்கள் விருப்பமான கேட்டரரை நேரடியாக தொடர்பு கொள்ளவும் — கீழே உள்ள கேட்டரர் பட்டியலைப் பார்க்கவும்.",
    prayersSuccessParticipantPaid: "வங்கி பரிமாற்றம் அல்லது DuitNow QR மூலம் பணம் செலுத்தி, மேலே உள்ள குறிப்பு எண்ணுடன் WhatsApp மூலம் பணம் செலுத்திய சான்றை அனுப்பவும்.",
    prayersSuccessParticipantFree: "நீங்கள் பதிவு செய்யப்பட்டுள்ளீர்கள். உங்களை சந்திக்க காத்திருக்கிறோம்!",
    prayersErrorGeneric: "ஏதோ தவறு நடந்தது. சிறிது நேரத்தில் மீண்டும் முயற்சிக்கவும்.", prayersCloseBtn: "மூடு",
    fridayAnnathanamHeading: "வாராந்திர வெள்ளி பூஜை அன்னதானம்",
    fridayAnnathanamSub: "RM 250 கோயிலின் ஒரு வெள்ளிக்கிழமை அன்னதான உணவை நிதியுதவி செய்கிறது. கீழே திறந்துள்ள எந்த வெள்ளிக்கிழமையையும் தேர்ந்தெடுத்து நிதியுதவி செய்யுங்கள் — வங்கி பரிமாற்றம் அல்லது DuitNow QR மூலம் பணம் செலுத்தலாம்.",
    fridayAnnathanamOpenBadge: "திறந்துள்ளது", fridayAnnathanamSponsoredBadge: "நிதியுதவி செய்யப்பட்டது", fridayAnnathanamSkippedBadge: "அன்னதானம் இல்லை",
    fridayAnnathanamSponsorBtn: "இந்த வெள்ளியை நிதியுதவி செய்ய", fridayAnnathanamModalTitle: "வெள்ளி அன்னதானத்தை நிதியுதவி செய்ய",
    fridayAnnathanamSuccessMessage: "உங்கள் வெள்ளி அன்னதான நிதியுதவி பதிவு செய்யப்பட்டுள்ளது. வங்கி பரிமாற்றம் அல்லது DuitNow QR மூலம் பணம் செலுத்தி, மேலே உள்ள குறிப்பு எண்ணுடன் WhatsApp மூலம் பணம் செலுத்திய சான்றை அனுப்பவும்.",
    fridayAnnathanamNoUpcoming: "இன்னும் வெள்ளிக்கிழமைகள் பட்டியலிடப்படவில்லை — விரைவில் மீண்டும் சரிபார்க்கவும்."
  },
  // Simplified Chinese (standard written Chinese as used in Malaysia — readable by
  // Cantonese, Hakka, Hokkien and Mandarin speakers alike). Brand and Tamil
  // ritual terms (Pooja, Annathanam, Ubayakarar, Seva) are kept in Latin script
  // on purpose so they match the signage devotees see at the temple.
  zh: {
    navHome: "首页", navAbout: "关于本庙", navCommittee: "庙宇理事会", navDeities: "神明",
    railBrandLine1: "Sri Subramaniar", railBrandLine2: "Alayam", railBrandLoc: "Lok Kawi，亚庇",
    navCalendar: "活动日历", navTimings: "Pooja 时间表", navGallery: "相册",
    navSevas: "Seva 与捐款", navNews: "最新消息与公告",
    navMembership: "会员状态", navContact: "联系我们",
    railHoursTitle: "庙宇开放时间 — 每日", railMorning: "早上", railEvening: "傍晚",
    heroEyebrow: "欢迎来到",
    heroTitleLine1: "Sri Subramaniar Alayam", heroTitleLine2: "Lok Kawi",
    statEstablished: "创立", statDevotees: "信徒", statEvents: "年度活动",
    heroBtnEvents: "近期活动", heroBtnTimings: "Pooja 时间表",
    panelTodayTimings: "今日 POOJA 时间", panelUpcomingEvents: "近期活动",
    panelNewsAnnouncements: "最新消息与公告",
    btnViewFullTimings: "查看完整时间表 →", btnViewFullCalendar: "查看完整日历 →",
    btnNewsAnnouncements: "最新消息与公告 →",
    velBlessing: "Vel! Vel! Vetri Vel!",
    velBlessingDesc: "愿穆鲁干神赐予您和家人平安、兴旺与健康。",
    subscribePlaceholder: "请输入您的电邮", subscribeBtn: "订阅",
    aboutHeading: "关于本庙", aboutSub: "了解 Sri Subramaniar Alayam 的历史、愿景与日常活动。",
    aboutHistoryTitle: "本庙历史", aboutVisionTitle: "愿景", aboutMissionTitle: "使命",
    aboutActivitiesTitle: "庙宇活动",
    committeeHeading: "庙宇管理理事会", committeeSub: "认识为 Sri Subramaniar Alayam 服务的理事。",
    committeeOfficersLabel: "执行职员", committeeMembersLabel: "理事",
    committeeAuditorsLabel: "内部审计员", committeeTrusteesLabel: "受托人",
    deitiesHeading: "神明", deitiesSub: "Sri Subramaniar 及本庙范围内的其他神明。",
    calendarHeading: "活动日历", calendarSub: "即将举行的 Pooja、庆典与特别活动。",
    calToday: "今天", calEventsSuffix: "活动", calNoEvents: "本月暂无活动记录。", readMoreBtn: "更多",
    timingsHeading: "Pooja 时间表", timingsSub: "每日 Pooja 时间表及特别日子的时间。",
    galleryHeading: "相册", gallerySub: "庆典、Pooja 与社区活动的珍贵时刻。",
    galleryBack: "返回", galleryEmpty: "暂无分类。", galleryFoldersEmpty: "暂无文件夹。", galleryPhotosEmpty: "暂无照片。",
    sevasHeading: "Seva 与捐款", sevasSub: "通过 Seva、赞助与捐款支持本庙。",
    donateBannerTitle: "每一份心意都很宝贵",
    donateBannerDesc: "您的慷慨捐助让每日 Pooja、庆典和社区活动得以持续举行，惠及成千上万的信徒。",
    newsHeading: "最新消息与公告", newsSub: "来自本庙的最新消息。",
    membershipHeading: "会员状态", membershipSub: "输入您的会员号码，查询您在本庙的会员状态。",
    membershipInputLabel: "会员号码", membershipPlaceholder: "M-0231",
    membershipCheckBtn: "查询状态", membershipChecking: "查询中…",
    membershipHint: "请输入会员卡上的会员号码。",
    membershipInvalidFormat: "请输入您的会员号码。",
    membershipNotFound: "找不到此会员号码的记录。",
    membershipError: "抱歉，出现错误。请稍后再试。",
    membershipResultName: "姓名", membershipResultNo: "会员号码",
    membershipResultType: "会员类别", membershipTypeLife: "终身会员", membershipTypeOrdinary: "普通会员",
    membershipResultStatus: "状态", membershipStatusActive: "有效", membershipStatusNotActive: "无效",
    membershipStatusPending: "待缴年费续会", membershipPrintBtn: "打印",
    contactHeading: "联系我们", contactSub: "欢迎莅临、来电或留言给我们。",
    getInTouch: "联系方式", regNoLabel: "注册号码", phoneLabel: "电话",
    emailLabel: "电邮", followLabel: "关注我们",
    enquiriesTitle: "如有任何查询", whatsappCaption: "扫码即可通过 WhatsApp 与我们联系",
    qrScanToPay: "扫码付款", qrAccountName: "户口名称", qrBank: "银行",
    qrAccountNo: "户口号码", qrNote: "请使用任何支持 DuitNow 的银行应用程序或电子钱包扫码。",
    idleReturning: "正在返回首页…",
    timingTabDaily: "每日", timingTabFriday: "星期五（特别）", timingTabFullMoon: "月圆日（Pournami）",
    navPrayers: "年度 Pooja 与报名",
    navFridayAnnathanam: "星期五 Annathanam",
    prayersHeading: "年度 Pooja 与报名", prayersSub: "赞助 Pooja 成为 Ubayakarar 或 Annathanam 赞助人，也可以报名参加。",
    prayersCategoryAnnual: "年度 Pooja", prayersCategoryMonthly: "每月 Pooja", prayersCategorySpecial: "特别 Pooja",
    prayersFilterAll: "全部", prayersFilterUpcoming: "即将举行", prayersFilterOver: "已结束",
    prayersStatusUpcoming: "即将举行", prayersStatusOver: "已结束",
    prayersUbayakararLabel: "Ubayakarar（赞助人）", prayersAnnathanamLabel: "Annathanam 赞助人", prayersParticipantLabel: "参加者",
    prayersOpenBadge: "开放", prayersTakenBadge: "已预订", prayersClosedBadge: "截止报名", prayersPaidBadge: "已付款", prayersNotPaidBadge: "未付款", prayersConfirmedBadge: "已确认", prayersNotConfirmedBadge: "未确认",
    prayersRegisterBtn: "报名", prayersFeeLabel: "Ubayam 费用", prayersPerPersonLabel: "每人", prayersAsArranged: "另行安排",
    prayersCaterersHeading: "Annathanam 餐饮承办商", prayersCaterersSub: "想自行安排餐食？欢迎直接联系我们的固定餐饮承办商。",
    prayersParticipantsHeading: "已报名参加者", prayersNoParticipants: "此 Pooja 暂无参加者报名记录。",
    prayersNotesLabel: "备注",
    prayersModalUbayakararTitle: "报名成为 Ubayakarar", prayersModalAnnathanamTitle: "报名成为 Annathanam 赞助人", prayersModalParticipantTitle: "报名参加",
    prayersFormName: "全名", prayersFormPhone: "电话 / WhatsApp 号码", prayersFormParticipantCount: "参加人数（总人数）",
    prayersFormParticipantCountHint: "以家庭或团体名义报名？请在此填写总人数，例如全家 5 人一同出席，请填 5。一次报名即涵盖所有人。",
    prayersPaxLabel: "人",
    prayersFormNotes: "备注（选填）", prayersFormSubmit: "提交报名", prayersFormSubmitting: "提交中…", prayersFormCancel: "取消",
    prayersSuccessTitle: "已收到您的报名！", prayersSuccessRef: "参考编号",
    prayersSuccessUbayakarar: "请通过银行转账或 DuitNow 二维码完成付款，然后通过 WhatsApp 发送付款凭证，并注明上方的参考编号。",
    prayersSuccessAnnathanam: "您的 Annathanam 赞助已预订。请直接联系您选择的餐饮承办商安排餐食 — 请见下方承办商名单。",
    prayersSuccessParticipantPaid: "请通过银行转账或 DuitNow 二维码完成付款，然后通过 WhatsApp 发送付款凭证，并注明上方的参考编号。",
    prayersSuccessParticipantFree: "您已成功报名。期待您的光临！",
    prayersErrorGeneric: "抱歉，出现错误。请稍后再试。", prayersCloseBtn: "关闭",
    fridayAnnathanamHeading: "每周星期五 Pooja Annathanam",
    fridayAnnathanamSub: "赞助本庙某个星期五的 Annathanam 餐食，费用为 RM 250。请在下方选择任何开放的星期五 — 可通过银行转账或 DuitNow 二维码付款。",
    fridayAnnathanamOpenBadge: "开放", fridayAnnathanamSponsoredBadge: "已有赞助", fridayAnnathanamSkippedBadge: "无 Annathanam",
    fridayAnnathanamSponsorBtn: "赞助本周五", fridayAnnathanamModalTitle: "赞助星期五 Annathanam",
    fridayAnnathanamSuccessMessage: "您的星期五 Annathanam 赞助已预订。请通过银行转账或 DuitNow 二维码完成付款，然后通过 WhatsApp 发送付款凭证，并注明上方的参考编号。",
    fridayAnnathanamNoUpcoming: "暂未列出任何星期五 — 请稍后再查看。"
  }
};

// ---------- Simplified Chinese home-tile copy (keyed by tile key) ----------
// Kept separate so tiles loaded from the database (which have no zh yet)
// still show Chinese text. Edit here until a zh field exists in the CMS.
const TILE_ZH = {
  about:            { title: "关于本庙",          desc: "历史、愿景与庙宇活动" },
  committee:        { title: "庙宇理事会",        desc: "管理理事会成员" },
  deities:          { title: "神明",              desc: "Sri Subramaniar 及其他神明" },
  calendar:         { title: "活动日历",          desc: "Pooja、庆典与特别活动" },
  timings:          { title: "Pooja 时间表",      desc: "每日 Pooja 与 Darshan 时间" },
  sevas:            { title: "Seva 与捐款",       desc: "支持本庙与 Seva" },
  prayers:          { title: "年度 Pooja 与报名", desc: "赞助或参加 Pooja" },
  fridayAnnathanam: { title: "星期五 Annathanam", desc: "赞助每周星期五的餐食" },
  membership:       { title: "会员状态",          desc: "查询您的会员状态" },
  gallery:          { title: "相册",              desc: "庙宇活动与庆典照片" }
};

// ---------- Home quick-nav tile copy (title/desc per language) ----------
const TILE_META = [
  { key: "about", icon: "about", destination: "about",
    title: { en: "About Temple", bm: "Tentang Kuil", ta: "கோயில் பற்றி" },
    desc:  { en: "History, Vision & Temple Activities", bm: "Sejarah, Visi & Aktiviti Kuil", ta: "வரலாறு, நோக்கம் & கோயில் நடவடிக்கைகள்" } },
  { key: "committee", icon: "committee", destination: "committee",
    title: { en: "Temple Committee", bm: "Jawatankuasa Kuil", ta: "கோயில் குழு" },
    desc:  { en: "Management Committee Members", bm: "Ahli Jawatankuasa Pengurusan", ta: "நிர்வாகக் குழு உறுப்பினர்கள்" } },
  { key: "deities", icon: "deities", destination: "deities",
    title: { en: "Deities", bm: "Dewa-Dewi", ta: "தெய்வங்கள்" },
    desc:  { en: "Sri Subramaniar & Other Deities", bm: "Sri Subramaniar & Dewa-Dewi Lain", ta: "ஸ்ரீ சுப்ரமணியர் & பிற தெய்வங்கள்" } },
  { key: "calendar", icon: "calendar", destination: "calendar",
    title: { en: "Event Calendar", bm: "Kalendar Acara", ta: "நிகழ்வு நாட்காட்டி" },
    desc:  { en: "Poojas, Festivals & Special Events", bm: "Pooja, Perayaan & Acara Khas", ta: "பூஜைகள், திருவிழாக்கள் & சிறப்பு நிகழ்வுகள்" } },
  { key: "timings", icon: "timings", destination: "timings",
    title: { en: "Pooja Timings", bm: "Waktu Pooja", ta: "பூஜை நேரங்கள்" },
    desc:  { en: "Daily Pooja & Darshan Timings", bm: "Waktu Pooja Harian & Darshan", ta: "தினசரி பூஜை & தரிசன நேரங்கள்" } },
  { key: "sevas", icon: "sevas", destination: "sevas",
    title: { en: "Sevas & Donations", bm: "Seva & Derma", ta: "சேவை & நன்கொடை" },
    desc:  { en: "Support Temple & Sevas", bm: "Sokong Kuil & Seva", ta: "கோயிலுக்கும் சேவைகளுக்கும் ஆதரவு" } },
  { key: "prayers", icon: "prayers", destination: "prayers",
    title: { en: "Prayers & Registration", bm: "Pooja Tahunan & Pendaftaran", ta: "ஆண்டு பூஜைகள் & பதிவு" },
    desc:  { en: "Sponsor or Join a Pooja", bm: "Taja atau Sertai Pooja", ta: "பூஜையை நிதியுதவி செய்ய அல்லது பங்கேற்க" } },
  { key: "fridayAnnathanam", icon: "fridayAnnathanam", destination: "fridayAnnathanam",
    title: { en: "Friday Annathanam", bm: "Annathanam Jumaat", ta: "வெள்ளி அன்னதானம்" },
    desc:  { en: "Sponsor a Weekly Friday Meal", bm: "Taja Hidangan Jumaat Mingguan", ta: "வாராந்திர வெள்ளி உணவை நிதியுதவி செய்ய" } },
  { key: "membership", icon: "membership", destination: "membership",
    title: { en: "Membership Status", bm: "Status Keahlian", ta: "உறுப்பினர் நிலை" },
    desc:  { en: "Check Your Membership Status", bm: "Semak Status Keahlian Anda", ta: "உங்கள் உறுப்பினர் நிலையைச் சரிபார்க்கவும்" } },
  { key: "gallery", icon: "gallery", destination: "gallery",
    title: { en: "Gallery", bm: "Galeri", ta: "படத்தொகுப்பு" },
    desc:  { en: "Photos from Temple Events & Festivals", bm: "Foto Acara & Perayaan Kuil", ta: "கோயில் நிகழ்வுகள் & திருவிழாக்களின் புகைப்படங்கள்" } }
];
