-- Seed data migrated from content/annual-prayers.json and content/caterers.json
insert into prayers (id, ref, date, name, ubayam_fee, ubayakarar_sponsor, ubayakarar_open, annathanam_sponsor, annathanam_open, participants_enabled, participant_fee, notes, status_override) values
  ('p1', 1, '2026-05-01', 'Chitra Pournami', NULL, 'Temple Committee', false, 'Terra Tech Borneo', false, true, NULL, '', NULL),
  ('p2', 2, '2026-05-21', 'MIC Kuttu Pirathanai', 150, 'MIC Sabah', false, 'Hare Rama', false, false, NULL, '', NULL),
  ('p3', 3, '2026-05-28', 'Andu Vila (Temple Anniversary)', NULL, 'Temple Committee', false, 'Breakfast: Mr. Sunny Louis / Dinner: Chandrasegar & Kamlesh', false, false, NULL, '', NULL),
  ('p4', 4, '2026-05-30', 'Vaikasi Visagam', 250, 'S.R. Abboo Arumugam & Lachami and Family', false, 'Mr. & Mrs. C. Silvan & C. Poovarasi', false, false, NULL, '', NULL),
  ('p5', 5, '2026-06-01', 'Guru Peyarchi', NULL, 'Devotees Collection', false, 'Mdm. Jaya / Mdm. Kamlesh', false, true, 31, 'Participation is by per-person contribution rather than a single Ubayakarar.', NULL),
  ('p6', 6, '2026-07-17', 'First Aadi Velli', 351, 'Dr. Mohanaprasanth & Fly', false, 'Dr. Mohanaprasanth & Fly', false, false, NULL, 'Annathanam is a separate arrangement, not included in the Ubayam fee.', NULL),
  ('p7', 7, '2026-07-24', 'Second Aadi Velli', 351, 'Edward Chia & Michelle Wong Family / Tan Syh Huei & Family / Yong Kun Shu & Family', false, 'Edward Chia & Michelle Wong Family / Tan Syh Huei & Family / Yong Kun Shu & Family', false, false, NULL, 'Annathanam is a separate arrangement, not included in the Ubayam fee.', NULL),
  ('p8', 8, '2026-07-31', 'Third Aadi Velli', 351, 'Group Ubayam', false, 'Group Annathanam', false, false, NULL, 'Annathanam is a separate arrangement, not included in the Ubayam fee.', NULL),
  ('p9', 9, '2026-08-03', 'Aadi Perukku', 351, 'Global Rich', false, 'Global Rich', false, false, NULL, 'Annathanam is a separate arrangement, not included in the Ubayam fee.', NULL),
  ('p10', 10, '2026-08-07', 'Aadi Krithigai (Nagamma Pongal)', 501, 'Mr. Raj', false, 'Mr. Raj', false, true, NULL, 'Participant list kept for the Thechatti offering. Annathanam is a separate arrangement, not included in the Ubayam fee.', NULL),
  ('p11', 11, '2026-08-14', 'Aadi Pooram', 351, 'Police', false, 'Police', false, false, NULL, 'Annathanam is a separate arrangement, not included in the Ubayam fee.', NULL),
  ('p12', 12, '2026-08-17', 'Garudan Panchami', 351, 'Gejalachumy Mithivanan', false, 'Gejalachumy Mithivanan', false, false, NULL, 'Annathanam is a separate arrangement, not included in the Ubayam fee.', NULL),
  ('p13', 13, '2026-08-21', 'Varalakshmi Viratham / Kuttu Vilakku Pooja', 351, 'Medisinar Klinik dan Surgeri Damai', false, 'Dr. Ganesh & Family / Dr. Vinoshine & Family', false, true, NULL, 'Annathanam is a separate arrangement, not included in the Ubayam fee.', NULL),
  ('p14', 14, '2026-09-04', 'Krishna Jeyanthi', 351, 'Mr. Sri Ram & Family', false, 'Mr. Sri Ram & Family', false, false, NULL, 'Annathanam is a separate arrangement, not included in the Ubayam fee.', NULL),
  ('p15', 15, '2026-09-14', 'Vinayagar Chathurthi', 501, 'Ms. Veronica / Mr. Ron', false, 'Ms. Veronica / Mr. Ron', false, false, NULL, 'Annathanam is a separate arrangement, not included in the Ubayam fee.', NULL),
  ('p16', 16, '2026-09-19', '1st Puratasi', 501, 'Mr. Chandrasegar & Mrs. Kamlesh (Morning & Night)', false, 'Mr. Chandrasegar & Mrs. Kamlesh (Morning & Night)', false, false, NULL, 'Annathanam is a separate arrangement, not included in the Ubayam fee.', NULL),
  ('p17', 17, '2026-09-26', '2nd Puratasi / Pournami', 351, 'Morning: Mr. & Mrs. Ravi Vasugi', true, 'Morning: Ravi Vasugi & Family, Suresh Jothi & Family, Murugiah Selvi & Family — Evening: Dr. Balan (UMS)', false, false, NULL, 'Two Ubayam slots on this date, RM 351 each — Morning is taken; the Evening slot is still open. Annathanam is a separate arrangement, not included in the Ubayam fee.', NULL),
  ('p18', 18, '2026-10-03', '3rd Puratasi', 1001, 'Mr. & Mrs. Balan Parimala (Morning & Night)', false, 'Mr. & Mrs. Balan Parimala (Morning & Night)', false, false, NULL, 'Annathanam is a separate arrangement, not included in the Ubayam fee.', NULL),
  ('p19', 19, '2026-10-10', '4th Puratasi', 351, NULL, true, 'Taken (sponsor name not recorded)', false, false, NULL, 'Two Ubayam slots on this date, RM 351 each — Morning and Evening, both still open.', NULL),
  ('p20', 20, '2026-10-11', 'Navarathiri Start (Durga Pooja)', 501, 'Medisinar', false, 'Medisinar', false, false, NULL, 'Annathanam is a separate arrangement, not included in the Ubayam fee.', NULL),
  ('p21', 21, '2026-10-12', 'Durga Pooja', 501, NULL, true, NULL, true, false, NULL, 'Evening Ubayam. Annathanam is a separate arrangement, not included in the Ubayam fee.', NULL),
  ('p22', 22, '2026-10-13', 'Durga Pooja', 501, NULL, true, NULL, true, false, NULL, 'Evening Ubayam. Annathanam is a separate arrangement, not included in the Ubayam fee.', NULL),
  ('p23', 23, '2026-10-14', 'Lakshmi Pooja', 501, '(confirmed — see committee records)', false, 'Crystal Chin Fui Yeing & Family / Anita Lee Mei Sin & Family / Tan Syh Huei & Family / Yong Kun Shu & Family / Edward Chia & Michelle Wong Family', false, false, NULL, 'Evening Ubayam, fee confirmed paid. Annathanam is a separate arrangement, not included in the Ubayam fee.', NULL),
  ('p24', 24, '2026-10-15', 'Lakshmi Pooja', 501, NULL, true, 'Mr. Kunasagran & Family', false, false, NULL, 'Evening Ubayam. Annathanam is a separate arrangement, not included in the Ubayam fee.', NULL),
  ('p25', 25, '2026-10-16', 'Lakshmi Pooja', 501, 'S.R. Abboo Arumugam & Lachami and Family', false, 'S.R. Abboo Arumugam & Lachami and Family', false, false, NULL, 'Evening Ubayam. Annathanam is a separate arrangement, not included in the Ubayam fee.', NULL),
  ('p26', 26, '2026-10-17', '5th Puratasi', 351, NULL, true, 'Taken (sponsor name not recorded)', false, false, NULL, 'Morning Ubayam.', NULL),
  ('p27', 27, '2026-10-17', 'Saraswathi Pooja', 501, NULL, true, NULL, true, false, NULL, 'Evening Ubayam. Annathanam is a separate arrangement, not included in the Ubayam fee.', NULL),
  ('p28', 28, '2026-10-18', 'Saraswathi Pooja', 501, NULL, true, NULL, true, false, NULL, 'Evening Ubayam. Annathanam is a separate arrangement, not included in the Ubayam fee.', NULL),
  ('p29', 29, '2026-10-19', 'Saraswathi Pooja', 501, NULL, true, NULL, true, false, NULL, 'Evening Ubayam. Annathanam is a separate arrangement, not included in the Ubayam fee.', NULL),
  ('p30', 30, '2026-10-20', 'Saraswathi Pooja (Ayudha Pooja)', 501, NULL, true, NULL, true, false, NULL, 'Evening Ubayam. Annathanam is a separate arrangement, not included in the Ubayam fee.', NULL),
  ('p31', 31, '2026-10-21', 'Vijaya Dasami', 1001, 'Mrs. Jeyadevi Gunaratnam', false, 'Mrs. Jeyadevi Gunaratnam', false, false, NULL, 'Annathanam is a separate arrangement, not included in the Ubayam fee.', NULL),
  ('p32', 32, '2026-11-08', 'Deepavali', 1001, NULL, true, NULL, true, false, NULL, 'Morning Ubayam. Annathanam is a separate arrangement, not included in the Ubayam fee.', NULL),
  ('p33', 33, '2026-11-10', 'Start of Kanda Shasti Fast', 501, NULL, true, NULL, true, true, NULL, 'Evening Ubayam. Annathanam is a separate arrangement, not included in the Ubayam fee.', NULL),
  ('p34', 34, '2026-11-11', 'Kanda Shasti Fast', 501, NULL, true, NULL, true, false, NULL, 'Evening Ubayam. Annathanam is a separate arrangement, not included in the Ubayam fee.', NULL),
  ('p35', 35, '2026-11-12', 'Kanda Shasti Fast', 501, NULL, true, NULL, true, false, NULL, 'Evening Ubayam. Annathanam is a separate arrangement, not included in the Ubayam fee.', NULL),
  ('p36', 36, '2026-11-13', 'Kanda Shasti Fast', 501, NULL, true, 'Dr. Muniswaran & Family', false, false, NULL, 'Evening Ubayam. Annathanam is a separate arrangement, not included in the Ubayam fee.', NULL),
  ('p37', 37, '2026-11-14', 'Kanda Shasti Fast', 501, NULL, true, 'Mr. Kunasagran & Family', false, false, NULL, 'Evening Ubayam. Annathanam is a separate arrangement, not included in the Ubayam fee.', NULL),
  ('p38', 38, '2026-11-15', 'Soora Samharam (End of Kanda Shasti Fast)', 1001, NULL, true, NULL, true, false, NULL, 'Evening Ubayam. Annathanam is a separate arrangement, not included in the Ubayam fee.', NULL),
  ('p39', 39, '2026-11-16', 'Kandha Sasthi Fast Breaking — Murugan / Vallitheivanai Thirukalyanam', 2001, NULL, true, 'Lunch: Mr. & Mrs. Balan Parimala', true, true, NULL, 'Morning: Abishegam / fast-breaking at 10 A.M. for Murugan/Vallitheivanai (no Ubayam charge). Evening: Thirukalyanam Ubayam, RM 2,001. Annathanam Lunch is sponsored; Dinner is still open.', NULL),
  ('p40', 40, '2026-11-24', 'Pournami / Karthigai Deepam', 1001, NULL, true, NULL, true, false, NULL, 'Abishegam Ubayam. Annathanam is a separate arrangement, not included in the Ubayam fee.', NULL),
  ('p41', 41, '2026-12-01', 'Kala Bhairava Ashtami (Group Pooja)', NULL, 'Group Ubayam', false, 'By Group', false, true, NULL, '', NULL),
  ('p42', 42, '2026-12-10', 'Hanuman Jayanthi', 351, 'Dr. Vishnu Varathan', false, 'Dr. Vishnu Varathan', false, false, NULL, 'Annathanam is a separate arrangement, not included in the Ubayam fee.', NULL),
  ('p43', 43, '2026-12-20', 'Vaikunda Ekadesi', 351, 'Mr. Chandrasegar & Mrs. Kamlesh', false, 'Mr. Chandrasegar & Mrs. Kamlesh', false, false, NULL, 'Evening Ubayam. Annathanam is a separate arrangement, not included in the Ubayam fee.', NULL),
  ('p44', 44, '2026-12-23', 'Thiruvathirai Abisegam / Pournami', 1001, NULL, true, 'Mr. Batumalai', false, false, NULL, 'Ubayam covers the Nadarajar Abishegam (morning Arudara Abishegam) ritual. Annathanam is a separate arrangement, not included in the Ubayam fee.', NULL),
  ('p45', 45, '2026-12-24', 'Thiruvathirai Darshanam', 1001, NULL, true, 'Mr. Batumalai', false, false, NULL, 'Ubayam covers the Nadarajar Abishegam (morning Arudara Abishegam) ritual. Annathanam is a separate arrangement, not included in the Ubayam fee.', NULL);

insert into caterers (name, contact, phone, sort_order) values
  ('Chennai Curry House', 'Cikgu Shan', '014-6542545', 0),
  ('Claypot Curry House', 'Mr. Sam', '016-5233858', 1),
  ('Mr. Sunny Louis', '', '016-8374935', 2),
  ('Mdm. Puvanesswari', '', '016-2880369', 3),
  ('Mdm. Thanam', '', '012-8269703', 4);
